#!/bin/bash

# input/output
METADATA_FILE="/usr/local/dataset/metadata.json"
PREDICTIONS_FILE="/usr/local/predictions.json"

# cd into working dir
cd /root

# source .envrc
source .envrc

# params
CLAIMANT_MODEL_FILE="models/claimant_model.json"
PRETRAINED_MODEL_NAME_OR_PATH="models/fnc"

python3 pipeline.py \
    --metadata_file ${METADATA_FILE} \
    --predictions_file ${PREDICTIONS_FILE} \
    --claimant_model_file ${CLAIMANT_MODEL_FILE} \
    --pretrained_model_name_or_path ${PRETRAINED_MODEL_NAME_OR_PATH} \
    --predict_batch_size 128 \
    --nproc 4
