#!/bin/bash

# input/output
METADATA_FILE="/usr/local/dataset/metadata.json"
PREDICTIONS_FILE="/usr/local/predictions.json"

# cd into working dir
cd /root

# source .envrc
source .envrc

# params
CLAIMANT_MODEL_FILE="models/claimant_model.json"
FNC_MODEL_DIR="models/fnc"
RERANK_MODEL_DIR="castorini/monobert-large-msmarco"

python3 pipeline.py \
    --metadata_file ${METADATA_FILE} \
    --predictions_file ${PREDICTIONS_FILE} \
    --claimant_model_file ${CLAIMANT_MODEL_FILE} \
    --fnc_model_dir ${FNC_MODEL_DIR} \
    --rerank_model_dir ${RERANK_MODEL_DIR} \
    --predict_batch_size 128 \
    --nproc 4
