#!/bin/bash

SRC_DIR="/usr/src"
CLAIMS_FILE="/usr/local/dataset/metadata.json"
ARTICLES_DIR="/usr/local/dataset/articles"
EXAMPLES_FILE="${SRC_DIR}/examples.json"
PREDICTIONS_FILE="/usr/local/predictions.txt"
WORD2VEC_FILE="${SRC_DIR}/models/GoogleNews-vectors-negative300.bin"
PRETRAINED_MODEL_NAME_OR_PATH="${SRC_DIR}/models/transformer/"

python3 ${SRC_DIR}/phase1-examples.py \
    --claims_file ${DATA_PATH} \
    --articles_dir ${ARTICLES_DIR} \
    --examples_file ${EXAMPLES_FILE} \
    --word2vec_file ${WORD2VEC_FILE} \
    --keep_n 5 \
    --min_threshold 0.40 \
    --min_exmaples 4 \
    --nproc 4

python3 ${SRC_DIR}/phase1-predict.py \
    --examples_file ${EXAMPLES_FILE} \
    --predictions_file ${PREDICTIONS_FILE} \
    --pretrained_model_name_or_path ${PRETRAINED_MODEL_NAME_OR_PATH} \
    --batch_size 4 \
